# -*- coding: utf-8 -*-
"""Day_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Sh1PMRkILMAu03LnQpCWvGnhFmdpLsK

# Hello World
"""

print('Hello World!')

"""Printing in Python

*Print* is a function. We pass the value/parameter what we want to print in the paranthesis.
"""

print('Hello World')
print(2+8)
print(3*6.8)
print("end")

"""Printing multiple arguments"""

print("hey can we meet up at", 5, "PM?")

"""# Strings

Basics of strings

> 


*   There's no difference between ' ' and " " in python
*   If we want to include ', enclose it within " "..... (" abc's")
"""

print("Hey is that abc's car?")

"""String concatenation"""

print("Hello "+"World")

"""Storing string in a variable"""

Name= "Brian"
print("Hey "+ Name)

"""taking string as input"""

name=input("Please enter your name: ")
print("Hey "+name)